# Generated by Django 6.0 on 2026-06-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='usario',
            new_name='usuario',
        ),
    ]
