# Generated by Django 6.0 on 2026-06-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='regalos/')),
                ('preferencias', models.ManyToManyField(blank=True, to='preferencias.preferencia')),
            ],
        ),
    ]
